hash: hashtable.cpp hashtable.h lab7driver.cpp
	g++ -Wall -g -c hashtable.cpp -o hashtable.o 
	g++ -Wall -g lab7driver.cpp hashtable.o -o hash

clean: 
	rm -f hash
	rm -f hashtable.o 
	rm -fr hash.dSYM/*
	
	rmdir hash.dSYM
